# Generated by Django 6.0.6 on 2026-06-15 00:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artikel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('konten', models.TextField()),
                ('kategori', models.CharField(default='Tips', max_length=50)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Artikel',
                'verbose_name_plural': 'Artikel',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pertanyaan', models.CharField(max_length=300)),
                ('jawaban', models.TextField()),
                ('urutan', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQ',
                'ordering': ['urutan', 'id'],
            },
        ),
        migrations.CreateModel(
            name='JurusanInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, unique=True)),
                ('icon', models.CharField(default='🎓', max_length=10)),
                ('deskripsi', models.TextField()),
                ('prospek', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Jurusan',
                'verbose_name_plural': 'Daftar Jurusan',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='HasilRekomendasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jurusan', models.CharField(max_length=100)),
                ('nilai_mat', models.IntegerField()),
                ('nilai_bhs', models.IntegerField()),
                ('nilai_ipa', models.IntegerField()),
                ('nilai_ips', models.IntegerField()),
                ('minat_tek', models.IntegerField()),
                ('minat_sen', models.IntegerField()),
                ('minat_bis', models.IntegerField()),
                ('minat_kes', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hasil Rekomendasi',
                'verbose_name_plural': 'Hasil Rekomendasi',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModelVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versi', models.CharField(max_length=20)),
                ('akurasi', models.FloatField(blank=True, null=True)),
                ('algoritma', models.CharField(default='Decision Tree', max_length=100)),
                ('dataset_size', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Aktif'), ('archived', 'Diarsipkan'), ('training', 'Sedang Training'), ('failed', 'Gagal')], default='active', max_length=20)),
                ('catatan', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Versi Model',
                'verbose_name_plural': 'Riwayat Versi Model',
                'ordering': ['-created_at'],
            },
        ),
    ]
