# Generated by Django 6.0.6 on 2026-06-15 01:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rekomendasi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JurusanDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, unique=True)),
                ('mata_kuliah', models.JSONField(default=list)),
                ('universitas', models.JSONField(default=list)),
                ('biaya_min', models.IntegerField(default=0)),
                ('biaya_max', models.IntegerField(default=0)),
                ('passing_grade', models.FloatField(default=0)),
                ('lama_studi', models.CharField(default='4 Tahun', max_length=20)),
                ('gelar', models.CharField(blank=True, max_length=50)),
                ('deskripsi_panjang', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Detail Jurusan',
                'verbose_name_plural': 'Detail Jurusan',
            },
        ),
        migrations.AddField(
            model_name='hasilrekomendasi',
            name='top3_data',
            field=models.JSONField(default=list),
        ),
        migrations.CreateModel(
            name='ProfilSiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sekolah', models.CharField(blank=True, max_length=200)),
                ('kelas', models.CharField(blank=True, max_length=20)),
                ('kota', models.CharField(blank=True, max_length=100)),
                ('bio', models.TextField(blank=True, max_length=300)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('poin', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil Siswa',
                'verbose_name_plural': 'Profil Siswa',
            },
        ),
        migrations.CreateModel(
            name='RiwayatPoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.IntegerField()),
                ('alasan', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riwayat_poin', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge', models.CharField(choices=[('pemula', '🧪 Pemula'), ('rajin', '🔁 Rajin Tes'), ('expert', '🏆 Expert'), ('profil_lengkap', '📋 Profil Lengkap'), ('poin_100', '⭐ Poin 100'), ('pembaca', '📰 Pembaca'), ('explorer', '🔍 Penjelajah')], max_length=30)),
                ('diraih_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Badge',
                'verbose_name_plural': 'Badges',
                'ordering': ['-diraih_at'],
                'unique_together': {('user', 'badge')},
            },
        ),
    ]
