# Generated by Django 6.0.6 on 2026-06-15 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rekomendasi', '0003_forumpost_forumcomment_testimoni'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AktivitasLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=150)),
                ('jenis', models.CharField(choices=[('login_gagal', '🔐 Login Gagal'), ('rate_limit', '🚫 Rate Limit Terlampaui'), ('akses_ditolak', '⛔ Akses Ditolak'), ('captcha_gagal', '🤖 CAPTCHA Gagal'), ('register_gagal', '📝 Register Gagal'), ('login_sukses', '✅ Login Sukses'), ('logout', '🚪 Logout'), ('session_timeout', '⏱️ Session Timeout')], max_length=30)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('keterangan', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aktivitas_log', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log Aktivitas',
                'verbose_name_plural': 'Log Aktivitas Keamanan',
                'ordering': ['-created_at'],
            },
        ),
    ]
